import type { ReportsAnalytics, ReportsPeriod, ScanLogEntry } from "../types";

const ANALYTICS_7_DAYS: ReportsAnalytics = {
  healthScoreTrend: [
    { label: "May 9", value: 5 },
    { label: "May 12", value: 6 },
    { label: "May 16", value: 7 },
    { label: "May 20", value: 6 },
    { label: "May 24", value: 7 },
    { label: "May 28", value: 8 },
    { label: "Jun 1", value: 7 },
  ],
  seoIssuesTrend: [
    { label: "May 9", value: 5 },
    { label: "May 12", value: 4 },
    { label: "May 16", value: 6 },
    { label: "May 20", value: 3 },
    { label: "May 24", value: 5 },
    { label: "May 28", value: 4 },
    { label: "Jun 1", value: 3 },
  ],
  notFoundTrend: [
    { label: "May 9", value: 3 },
    { label: "May 12", value: 5 },
    { label: "May 16", value: 4 },
    { label: "May 20", value: 6 },
    { label: "May 24", value: 5 },
    { label: "May 28", value: 7 },
    { label: "Jun 1", value: 6 },
  ],
  weeklyChanges: [
    { label: "Apr W3", value: 3 },
    { label: "Apr W4", value: 5 },
    { label: "May W1", value: 4 },
    { label: "May W2", value: 6 },
    { label: "May W3", value: 5 },
    { label: "May W4", value: 7 },
    { label: "Jun W1", value: 6 },
  ],
};

const ANALYTICS_30_DAYS: ReportsAnalytics = {
  healthScoreTrend: [
    { label: "May 1", value: 4 },
    { label: "May 5", value: 5 },
    { label: "May 9", value: 5 },
    { label: "May 13", value: 6 },
    { label: "May 17", value: 7 },
    { label: "May 21", value: 6 },
    { label: "May 25", value: 7 },
    { label: "May 29", value: 8 },
    { label: "Jun 1", value: 7 },
  ],
  seoIssuesTrend: [
    { label: "May 1", value: 6 },
    { label: "May 5", value: 5 },
    { label: "May 9", value: 5 },
    { label: "May 13", value: 4 },
    { label: "May 17", value: 6 },
    { label: "May 21", value: 3 },
    { label: "May 25", value: 5 },
    { label: "May 29", value: 4 },
    { label: "Jun 1", value: 3 },
  ],
  notFoundTrend: [
    { label: "May 1", value: 4 },
    { label: "May 5", value: 3 },
    { label: "May 9", value: 3 },
    { label: "May 13", value: 5 },
    { label: "May 17", value: 4 },
    { label: "May 21", value: 6 },
    { label: "May 25", value: 5 },
    { label: "May 29", value: 7 },
    { label: "Jun 1", value: 6 },
  ],
  weeklyChanges: [
    { label: "Apr W1", value: 2 },
    { label: "Apr W2", value: 4 },
    { label: "Apr W3", value: 3 },
    { label: "Apr W4", value: 5 },
    { label: "May W1", value: 4 },
    { label: "May W2", value: 6 },
    { label: "May W3", value: 5 },
    { label: "May W4", value: 7 },
    { label: "Jun W1", value: 6 },
  ],
};

const ANALYTICS_90_DAYS: ReportsAnalytics = {
  healthScoreTrend: [
    { label: "Mar", value: 3 },
    { label: "Apr", value: 5 },
    { label: "May", value: 7 },
    { label: "Jun", value: 8 },
  ],
  seoIssuesTrend: [
    { label: "Mar", value: 6 },
    { label: "Apr", value: 5 },
    { label: "May", value: 4 },
    { label: "Jun", value: 3 },
  ],
  notFoundTrend: [
    { label: "Mar", value: 5 },
    { label: "Apr", value: 4 },
    { label: "May", value: 6 },
    { label: "Jun", value: 5 },
  ],
  weeklyChanges: [
    { label: "Mar W2", value: 2 },
    { label: "Mar W4", value: 3 },
    { label: "Apr W2", value: 4 },
    { label: "Apr W4", value: 5 },
    { label: "May W2", value: 6 },
    { label: "May W4", value: 7 },
    { label: "Jun W1", value: 6 },
  ],
};

export const MOCK_ANALYTICS_BY_PERIOD: Record<ReportsPeriod, ReportsAnalytics> = {
  7: ANALYTICS_7_DAYS,
  30: ANALYTICS_30_DAYS,
  90: ANALYTICS_90_DAYS,
};

export const MOCK_SCAN_LOG: ScanLogEntry[] = [
  {
    id: "1",
    status: "completed",
    trigger: "manual",
    pages_crawled: 142,
    created_at: "2026-05-31T00:00:00Z",
    finished_at: "2026-05-31T00:04:12Z",
    health_score: null,
  },
  {
    id: "2",
    status: "completed",
    trigger: "manual",
    pages_crawled: 138,
    created_at: "2026-05-24T00:00:00Z",
    finished_at: "2026-05-24T00:04:01Z",
    health_score: null,
  },
  {
    id: "3",
    status: "completed",
    trigger: "manual",
    pages_crawled: 135,
    created_at: "2026-05-17T00:00:00Z",
    finished_at: "2026-05-17T00:03:55Z",
    health_score: null,
  },
  {
    id: "4",
    status: "completed",
    trigger: "manual",
    pages_crawled: 130,
    created_at: "2026-05-10T00:00:00Z",
    finished_at: "2026-05-10T00:03:48Z",
    health_score: null,
  },
  {
    id: "5",
    status: "completed",
    trigger: "manual",
    pages_crawled: 128,
    created_at: "2026-05-03T00:00:00Z",
    finished_at: "2026-05-03T00:03:40Z",
    health_score: null,
  },
];
