// TODO: MOCK DATA — remove this file and set USE_MOCK_SUMMARY = false in api.ts when the backend is ready
import type { IssueSummary } from "../types";

function sparkline(values: number[]): { label: string; value: number }[] {
  return values.map((value, i) => ({ label: String(i), value }));
}

export const MOCK_ISSUE_SUMMARY: IssueSummary = {
  executive_summary:
    "ارتفعت الزيارات هذا الأسبوع بنسبة 18%، لكن معدل التحويل انخفض بنسبة 11%. جاء معظم هذا التراجع من زوّار الأجهزة المحمولة مع ضعف التفاعل مع صفحة التسعير، بينما واصلت الزيارات العضوية نموّها بثبات.",
  period_days: 30,
  performance_score: 87,
  confidence_rate: 92,
  generated_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  trends: [
    { metric: "الزيارات", value: 18, direction: "up", tone: "positive" },
    { metric: "معدل التحويل", value: 11, direction: "down", tone: "negative" },
    { metric: "تفاعل الجوال", value: 32, direction: "down", tone: "warning" },
  ],
  key_metrics: [
    {
      label: "معدل الارتداد",
      value: "29.4",
      unit: "%",
      change: -3.2,
      previousPeriodLabel: "الفترة السابقة",
      sparkline: sparkline([34, 33, 32, 31, 30.5, 30, 29.8, 29.4]),
    },
    {
      label: "الإيرادات",
      value: "312K",
      unit: " ريال",
      change: 9,
      previousPeriodLabel: "الفترة السابقة",
      sparkline: sparkline([260, 270, 280, 290, 295, 300, 305, 312]),
    },
    {
      label: "معدل التحويل",
      value: "2.4",
      unit: "%",
      change: -11,
      previousPeriodLabel: "الفترة السابقة",
      sparkline: sparkline([3.1, 3.0, 2.9, 2.8, 2.7, 2.6, 2.5, 2.4]),
    },
    {
      label: "الجلسات",
      value: "31,420",
      change: 9.3,
      previousPeriodLabel: "الفترة السابقة",
      sparkline: sparkline([26500, 27200, 28100, 28900, 29700, 30300, 30900, 31420]),
    },
    {
      label: "المستخدمون",
      value: "24,831",
      change: 12.4,
      previousPeriodLabel: "الفترة السابقة",
      sparkline: sparkline([19800, 20500, 21300, 22100, 22800, 23400, 24100, 24831]),
    },
  ],
  work_performance: {
    weaknesses: ["تحويل الجوال", "تفاعل صفحة التسعير"],
    strengths: ["الزيارات العضوية", "سرعة تحميل الموقع"],
    confidence: 92,
    growthTrend: 8,
    status: "ممتاز",
  },
  critical_insights: [
    { title: "انخفاض المستخدمين العائدين", category: "الجمهور", change: -14, tone: "negative" },
    { title: "انخفاض معدل التحويل", category: "التحويل", change: -11, tone: "negative" },
    { title: "نمو الزيارات العضوية", category: "مصادر الزيارات", change: 22, tone: "positive" },
  ],
  smart_insights: [
    {
      category: "التفاعل",
      severity: "medium",
      title: "ارتفاع معدل الارتداد",
      description:
        "زاد معدل الارتداد بشكل ملحوظ على صفحات الهبوط، خصوصاً القادمة من الإعلانات.",
      metrics: [
        { label: "مدة الجلسة", value: "-4%" },
        { label: "معدل الارتداد", value: "+6%" },
      ],
    },
    {
      category: "الجمهور",
      severity: "critical",
      title: "انخفاض المستخدمين العائدين",
      description: "تراجع عدد الزوار العائدين خلال آخر 30 يوماً، ما يشير إلى ضعف في الاحتفاظ بالعملاء.",
      metrics: [
        { label: "الجلسات", value: "-7%" },
        { label: "العائدون", value: "-14%" },
      ],
    },
    {
      category: "الأجهزة",
      severity: "positive",
      title: "تحسّن تفاعل الجوال",
      description: "ارتفع متوسط مدة الجلسة على الأجهزة المحمولة بعد تحسينات سرعة تحميل الصفحات.",
      metrics: [
        { label: "مدة الجلسة", value: "+9%" },
        { label: "الصفحات/جلسة", value: "+5%" },
      ],
    },
    {
      category: "مصادر الزيارات",
      severity: "positive",
      title: "نمو الزيارات العضوية",
      description: "تواصل النمو العضوي من نتائج البحث القوي نتيجة تحسّن الترتيب في كلمات مفتاحية رئيسية.",
      metrics: [
        { label: "الظهور", value: "+18%" },
        { label: "عضوية", value: "+22%" },
      ],
    },
    {
      category: "المحتوى",
      severity: "positive",
      title: "صفحات محتوى عالية الأداء",
      description: "خمس مقالات حقّقت أطول مدة بقاء وأعلى نسبة مشاركة بين كل المحتوى.",
      metrics: [
        { label: "المشاركات", value: "+24%" },
        { label: "مدة البقاء", value: "+18%" },
      ],
    },
    {
      category: "SEO",
      severity: "positive",
      title: "تحسّن ترتيب كلمات مفتاحية",
      description: "ارتفع ترتيب 12 كلمة مفتاحية نحو الصفحة الأولى، ما يعزّز الظهور العضوي.",
      metrics: [
        { label: "متوسط الترتيب", value: "+4" },
        { label: "كلمات صاعدة", value: "+12" },
      ],
    },
  ],
  root_cause_analysis: [
    {
      issue: "انخفاض معدل التحويل",
      cause: "بطء تحميل صفحات الدفع على الأجهزة المحمولة",
      priority: "high",
      frequency: 19,
    },
    {
      issue: "نمو الزيارات المشبوهة",
      cause: "ارتفاع حركة البوتات من مصادر خارجية",
      priority: "medium",
      frequency: 7,
    },
    {
      issue: "ضعف معدل التفاعل",
      cause: "المحتوى لا يتطابق مع نية البحث للكلمات المفتاحية المستهدفة",
      priority: "medium",
      frequency: 4,
    },
  ],
  root_cause_details: [
    {
      issue: "معدل التحويل",
      cause: "-11%",
      causes: [
        { severity: "high", text: "انخفضت مدة الجلسة بشكل ملحوظ" },
        { severity: "medium", text: "تغيّرت جودة الزيارات العضوية الواردة" },
        { severity: "high", text: "تراجع التفاعل مع صفحة التسعير" },
        { severity: "medium", text: "انخفض عدد المستخدمين العائدين" },
      ],
      affectedPages: ["/checkout", "/pricing"],
      confidenceLevel: "high",
      confidence: 85,
    },
    {
      issue: "معدل الارتداد",
      cause: "+6%",
      causes: [],
      affectedPages: [],
      confidenceLevel: "medium",
      confidence: 60,
    },
    {
      issue: "مدة الجلسة",
      cause: "-4%",
      causes: [],
      affectedPages: [],
      confidenceLevel: "medium",
      confidence: 55,
    },
  ],
  growth_opportunities: [
    {
      title: "كلمات مفتاحية قريبة من الصفحة الأولى",
      description: "12 كلمة مفتاحية تظهر في المراكز 11–15؛ دفعها بمحتوى بسيط قد تنقلها إلى الصفحة الأولى.",
      potential: "high",
      expectedImpact: "+1,800 زيارة شهرياً",
      difficulty: "medium",
    },
    {
      title: "مرات ظهور عالية مع نقرات منخفضة",
      description: "صفحات تظهر كثيراً في نتائج البحث لكن نسبة نقرها ضعيفة؛ تحسين العناوين الوصفية يرفع النقرات.",
      potential: "high",
      expectedImpact: "3.2% نسبة النقر",
      difficulty: "low",
    },
    {
      title: "صفحات هبوط واعدة دون استغلال",
      description: "5 صفحات بزيارات عالية ونحويل منخفض؛ تحسينها يحقق مكاسب سريعة في الأداء.",
      potential: "high",
      expectedImpact: "+0.9% تحويل",
      difficulty: "medium",
    },
    {
      title: "نمو سريع في زيارات الإحالة",
      description: "ارتفعت زيارات الإحالة من مواقع شريكة بنسبة 46%؛ قناة نمو ناشئة تستحق الاستثمار.",
      potential: "medium",
      expectedImpact: "قناة نمو ناشئة",
      difficulty: "low",
    },
  ],
  recommendations: [
    {
      id: "rec-1",
      title: "تحسين صفحة التسعير",
      description:
        "إعادة تصميم صفحة التسعير لإبراز القيمة بوضوح وتبسيط مقارنة الخطط وإضافة دعوة واضحة لاتخاذ الإجراء.",
      priority: "high",
      why: "زيارات عالية مع معدل تحويل ضعيف على هذه الصفحة تحديداً.",
      effort: "medium",
      expected_impact: "+1.4% رفع التحويل",
      estimatedTime: "3 أيام",
      affectedPage: "/pricing",
      category: "التحويل",
      confidence: 91,
    },
    {
      id: "rec-2",
      title: "تبسيط مسار الدفع على الجوال",
      description:
        "تقليل عدد الحقول وخطوات الدفع على الأجهزة المحمولة، وتفعيل الدفع السريع لتسريع إتمام الطلب.",
      priority: "high",
      why: "معظم تراجع التحويل جاء من زوّار الأجهزة المحمولة.",
      effort: "high",
      expected_impact: "+0.8% رفع التحويل",
      estimatedTime: "5 أيام",
      affectedPage: "/checkout",
      category: "الجوال",
      confidence: 88,
    },
    {
      id: "rec-3",
      title: "حملة إعادة استهداف للعائدين",
      description: "إطلاق حملة بريدية وإعلانية موجهة لاستعادة المستخدمين العائدين الذين توقفوا عن التفاعل.",
      priority: "medium",
      why: "انخفض عدد المستخدمين العائدين بنسبة 14% خلال الشهر.",
      effort: "low",
      expected_impact: "+6% رفع الاحتفاظ",
      estimatedTime: "يومان",
      affectedPage: "حملات بريدية",
      category: "الاحتفاظ",
      confidence: 76,
    },
    {
      id: "rec-4",
      title: "زيادة المحتوى العضوي",
      description: "إنشاء محتوى يستهدف الكلمات المفتاحية القريبة من الصفحة الأولى لزيادة الزيارات العضوية تدريجياً.",
      priority: "low",
      why: "كلمات مفتاحية في المراكز 11–15 قابلة للتصدر بجهد بسيط.",
      effort: "medium",
      expected_impact: "+1,800 زيارة",
      estimatedTime: "أسبوعان",
      affectedPage: "/blog",
      category: "المحتوى",
      confidence: 68,
    },
  ],
  recommendation_tracking: [
    {
      id: "track-1",
      title: "تحسين صفحة التسعير",
      category: "معدل التحويل",
      status: "completed",
      before: 2.4,
      after: 3.8,
      assignee: "سارة لـ",
      date: "5 يوليو",
    },
    {
      id: "track-2",
      title: "تبسيط الدفع على الجوال",
      category: "تجربة الجوال",
      status: "in_progress",
      progress: 60,
      assignee: "أحمد م.",
      date: "12 يوليو",
    },
    {
      id: "track-3",
      title: "حملة إعادة استهداف العائدين",
      category: "الاحتفاظ",
      status: "not_started",
      assignee: "غير محدّد",
      date: "20 يوليو",
    },
  ],
  performance_history: {
    chartData: sparkline([180, 210, 230, 250, 260, 270, 280, 300, 295, 310, 330]).map((p, i) => ({
      ...p,
      label: ["يناير", "مارس", "مايو", "يوليو", "سبتمبر", "نوفمبر"][Math.floor(i / 2)] ?? p.label,
    })),
    metrics: [
      { label: "المستخدمون", value: "24,831", change: 12 },
      { label: "الإيرادات", value: "312K ريال", change: 9 },
      { label: "معدل التحويل", value: "2.4%", change: -11 },
      { label: "الزيارات", value: "31,420", change: 18 },
    ],
    timeline: [
      { tag: "result", title: "تحسّن في معدل التحويل", date: "5 يونيو 2026" },
      { tag: "event", title: "ارتفاع مفاجئ في الزيارات", date: "28 مايو 2026" },
      { tag: "recommendation", title: "تطبيق توصية الذكاء الاصطناعي", date: "22 مايو 2026" },
      { tag: "seo", title: "تحسين تقني لـ SEO", date: "15 مايو 2026" },
      { tag: "update", title: "تحديث صفحة الهبوط", date: "8 مايو 2026" },
      { tag: "campaign", title: "بدء حملة تسويقية", date: "1 مايو 2026" },
    ],
    comparison: [
      {
        status: "stable",
        rows: [
          { label: "معدل الارتداد", value: "±0.5%" },
          { label: "الصفحات/جلسة", value: "±0%" },
        ],
      },
      {
        status: "declined",
        rows: [
          { label: "معدل التحويل", value: "-11%" },
          { label: "العائدون", value: "-14%" },
          { label: "مدة الجلسة", value: "-4%" },
        ],
      },
      {
        status: "improved",
        rows: [
          { label: "الزيارات", value: "+18%" },
          { label: "الإيرادات", value: "+9%" },
          { label: "المستخدمون", value: "+12%" },
          { label: "مرات الظهور", value: "+15%" },
        ],
      },
    ],
    learningStats: {
      conversionLift: "+1.3 نقطة",
      revenueLift: "+84K ريال",
      successfulRecs: 7,
      appliedRecs: 9,
      generatedRecs: 12,
      successRate: 78,
      periodLabel: "آخر 90 يوماً",
    },
  },
};
